### ISSUE TITLE
Problem displaying mnist-8.onnx

### ISSUE THREAD

**Issue by GeorgeS2019** [fel88/Dendrite#3]
I just tried to further feedback the latest Dagre layout feature by loading [mnist-8.onnx](https://github.com/onnx/models/blob/master/vision/classification/mnist/model/mnist-8.onnx) and compare the Dagre layout with the [layout displayed here](https://nietras.com/2021/03/20/introducing-onnxsharp/) by Netron. The Dagre layout does not work. Please use this to diagnose bugs.

![image](https://user-images.githubusercontent.com/49812372/133985677-d5db2303-4126-4404-a829-9d5d12ae4b81.png)

**Comment by fel88** [comment]
Got it. I'll fix it out

**Comment by fel88** [comment]
I fixed some bugs and now it looks better

![image](https://user-images.githubusercontent.com/15663687/134205272-add519f8-8e1a-40f8-a57a-827fee0c3e81.png)
